# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163M_pnfvIUdUhN7VvONzy3mpyLXCHhv0
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.path as mpath
import random

# Konfiguracja strony Streamlit
st.set_page_config(page_title="Mikołaj w Pythonie", page_icon="🎅")

def narysuj_mikolaja(ilosc_sniegu):
    """
    Funkcja generuje figurę matplotlib z rysunkiem Mikołaja.
    Zwraca obiekt fig.
    """
    # 1. Konfiguracja płótna (Object-Oriented approach)
    fig, ax = plt.subplots(figsize=(6, 8))
    ax.set_aspect('equal')
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 12)
    ax.axis('off')  # Ukrycie osi

    # Paleta kolorów
    skora = '#ffe0bd'
    czerwony = '#d40000'
    bialy = '#f8f8f8'
    czarny = '#1a1a1a'
    zloty = '#ffcc00'

    # --- TŁO (ŚNIEG) ---
    # Dodajemy prostokąt tła, żeby śnieg był lepiej widoczny na różnych motywach Streamlit
    tlo = patches.Rectangle((0, 0), 10, 12, color="#eef7fa")
    ax.add_patch(tlo)

    for _ in range(ilosc_sniegu):
        x = random.uniform(0, 10)
        y = random.uniform(0, 12)
        r = random.uniform(0.05, 0.15)
        # Niebieskawy śnieg
        ax.add_patch(patches.Circle((x, y), r, color='#ffffff', alpha=0.8))

    # --- 1. TUŁÓW I NOGI ---
    # Buty
    ax.add_patch(patches.Ellipse((3.8, 0.8), 1.2, 1, color=czarny))
    ax.add_patch(patches.Ellipse((6.2, 0.8), 1.2, 1, color=czarny))

    # Główna bryła płaszcza
    tulow = patches.Ellipse((5, 4), 5, 7, color=czerwony)
    ax.add_patch(tulow)

    # Biały pas na środku płaszcza
    ax.add_patch(patches.Rectangle((4.6, 2), 0.8, 6, color=bialy))

    # --- 2. PAS ---
    pas = patches.Rectangle((2.5, 3.8), 5, 0.8, color=czarny)
    ax.add_patch(pas)
    # Złota klamra
    ax.add_patch(patches.Rectangle((4.5, 3.7), 1.0, 1.0, color=zloty))
    ax.add_patch(patches.Rectangle((4.7, 3.9), 0.6, 0.6, color=czarny))

    # --- 3. RĘCE ---
    reka_lewa = patches.Ellipse((3, 6), 3, 1.2, angle=30, color=czerwony)
    reka_prawa = patches.Ellipse((7, 6), 3, 1.2, angle=-30, color=czerwony)
    ax.add_patch(reka_lewa)
    ax.add_patch(reka_prawa)

    # Rękawice
    ax.add_patch(patches.Circle((1.8, 5), 0.5, color=czarny))
    ax.add_patch(patches.Circle((8.2, 5), 0.5, color=czarny))

    # --- 4. BRODA (ŁĄCZNIK) ---
    srodki_brody = [(5, 6.5), (4.2, 6.8), (5.8, 6.8), (4.5, 6), (5.5, 6), (5, 5.5)]
    for bx, by in srodki_brody:
        ax.add_patch(patches.Circle((bx, by), 0.8, color=bialy))

    # --- 5. GŁOWA ---
    glowa = patches.Circle((5, 7.8), 1.3, color=skora)
    ax.add_patch(glowa)

    # --- 6. CZAPKA ---
    ksztalt_czapki = [[3.5, 8.5], [6.5, 8.5], [5, 11]]
    czapka = patches.Polygon(ksztalt_czapki, closed=True, color=czerwony)
    ax.add_patch(czapka)
    ax.add_patch(patches.FancyBboxPatch((3.4, 8.2), 3.2, 0.7, boxstyle="round,pad=0.1", color=bialy))
    ax.add_patch(patches.Circle((5, 11), 0.5, color=bialy))

    # --- 7. TWARZ (DETALE) ---
    ax.add_patch(patches.Circle((4.6, 8.0), 0.12, color=czarny)) # Oko L
    ax.add_patch(patches.Circle((5.4, 8.0), 0.12, color=czarny)) # Oko P
    ax.add_patch(patches.Circle((5, 7.6), 0.2, color='#ffaaaa')) # Nos
    # Wąsy
    ax.add_patch(patches.Ellipse((4.6, 7.3), 0.8, 0.4, angle=20, color=bialy))
    ax.add_patch(patches.Ellipse((5.4, 7.3), 0.8, 0.4, angle=-20, color=bialy))

    return fig

# --- INTERFEJS STREAMLIT ---

st.title("🎅 Generator Mikołaja")
st.markdown("Ten prosty kod używa `matplotlib` do narysowania Mikołaja z geometrycznych kształtów.")

# Interaktywny suwak
ilosc_sniegu = st.slider("Jak mocno ma padać śnieg?", min_value=0, max_value=300, value=60)

# Przycisk do odświeżania (losuje nowy układ śniegu)
if st.button("Odśwież / Nowy śnieg"):
    pass # Streamlit i tak przeliczy skrypt od nowa

# Generowanie i wyświetlanie
figura = narysuj_mikolaja(ilosc_sniegu)

# WAŻNE: W Streamlit używamy st.pyplot() zamiast plt.show()
st.pyplot(figura)
